### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by ollieh** [adnelson/nix-node-packages#26]
d-0.1.1 depends on es5-ext-0.10.11
es5-ext-0.10.11 depends on es6-iterator-2.0.0 which depends back on es5-ext-0.10.11 and d-0.1.1
es6-iterator-2.0.0 also depends on es6-symbol-3.0.2 which depends back on es5-ext-0.10.11 and d-0.1.1

Not sure if this is intended or not.

**Comment by adnelson** [comment]
So this kind of thing is the result of the way npm handles packages. It allows for circular dependencies, which is a very bad design decision IMO but they do pop up.

The solution is to patch the problematic packages themselves, either by removing the dependency that is circular, or providing a custom derivation which satisfies the dependency in a way that doesn't produce circularity.

**Comment by adnelson** [comment]
I should mention that the original `buildNodePackage` function, in the `nixpkgs` collection and from which the one here has been (heavily) modified, did handle circularity, but (a) it did it via shims, which is confusing and also doesn't guarantee that the package will actually work at runtime, and (b) means that expression evaluation is super slow because every package has to recur through its entire dependency tree searching for itself (essentially it's _O_(_n<sup>2</sup>_) which means it can take up to a minute or more on some of the more complex packages)

**Comment by adnelson** [comment]
@ollieh 

I patched the four packages you mentioned and added a section to the README on how to do the same with similar situations. Hopefully there aren't too many, or else it would probably be good to add logic to `buildNodePackage` to do this programmatically.

**Comment by ollieh** [comment]
@adnelson Thanks so much!

**Comment by adnelson** [comment]
No problem! Hopefully those packages work fine. :grimacing:  I haven't tested their usage, only that they build OK. But from what I understand about node's import system, it seems OK.
